### ISSUE TITLE
no rocker device

### ISSUE THREAD

**Issue by newuser** [scottfeldman/qemu-rocker#4]
I used instruction to this repository, however qemu-system-x86_64 -device help 2>&1 | grep rocker didn't show rocker device. config-devices.mk has default setting from git CONFIG_ROCKER=y.

**Comment by scottfeldman** [comment]
I get this:

~/qemu$ ./x86_64-softmmu/qemu-system-x86_64 -device help 2>&1 | grep rocker
name "rocker", bus PCI, desc "Rocker Switch"

Maybe try:

make distclean
./configure --target-list=x86_64-softmmu --extra-cflags=-DDEBUG_ROCKER
make -j8
./x86_64-softmmu/qemu-system-x86_64 -device help 2>&1 | grep rocker

Also, make sure you're on "master" branch.  git checkout master.

**Comment by newuser** [comment]
Oh, sorry, I messed with previously installed qemu.
